\# Copyright (C) 2002-3 Bruce Allen <smartmontools-support@lists.sourceforge.net>
\# 
\# $Id: smartd.8,v 1.83 2003/04/10 09:40:36 ballen4705 Exp $
\#
\# This program is free software; you can redistribute it and/or modify it
\# under the terms of the GNU General Public License as published by the Free
\# Software Foundation; either version 2, or (at your option) any later
\# version.
\# 
\# You should have received a copy of the GNU General Public License (for
\# example COPYING); if not, write to the Free Software Foundation, Inc., 675
\# Mass Ave, Cambridge, MA 02139, USA.
\# 
\# This code was originally developed as a Senior Thesis by Michael Cornwell
\# at the Concurrent Systems Laboratory (now part of the Storage Systems
\# Research Center), Jack Baskin School of Engineering, University of
\# California, Santa Cruz. http://ssrc.soe.ucsc.edu/
\#
.TH SMARTD 8  "$Date: 2003/04/10 09:40:36 $" "smartmontools-5.1"
.SH NAME
smartd \- S.M.A.R.T. Daemon
.SH SYNOPSIS
.B smartd [options]

.SH DESCRIPTION
.B smartd
is a daemon that monitors the Self-Monitoring, Analysis and Reporting
Technology (S.M.A.R.T.) system built into many ATA-3 and later ATA,
IDE and SCSI-3 hard drives. The purpose of S.M.A.R.T. is to monitor
the reliability of the hard drive and predict drive failures, and to
carry out different types of drive self-tests.  This version of
.B smartd
is compatible with ATA/ATAPI-5 and earlier standards (see 
.B REFERENCES
below)

.B smartd
will attempt to enable S.M.A.R.T. monitoring on ATA devices (equivalent to
.B smartctl -s on
) and polls
these and SCSI devices every 30 minutes (configurable), logging
S.M.A.R.T. errors and changes of S.M.A.R.T. Attributes via the SYSLOG
interface.  The default location for these SYSLOG notifications and
warnings is
.B /var/log/messages. 

.B smartd
can be configured at start-up using the file
.B /etc/smartd.conf.
Note that
.B smartd
only reads the configuration file at start-up: changes to the
configuration file take effect only after the
.B smartd
daemon is restarted.
If you send a 
.B HUP
signal to
.B smartd
it will log a polite message saying that it ignores this signal and
that it has
.I not
re-read the configuration file.

If you send a 
.B USR1 
signal to
.B smartd
it will immediately check the status of the disks, and then return to
polling the disks every 30 minutes. See the
.B '\-i'
option below for additional details.

On startup, in the absence of the configuration file
.B /etc/smartd.conf,
the 
.B smartd
daemon first scans for all devices that support S.M.A.R.T., using
.B "/dev/hd[a-l]"
for IDE/ATA devices, and 
.B "/dev/sd[a-z]"
for SCSI devices. It then monitors for
.I all 
possible S.M.A.R.T. errors (corresponding to the 
.B '\-a' 
Directive in the configuration file; see
.B CONFIGURATION FILE
below). Note that when there is no configuration file, and
.B smartd
scans for devices on startup,
.B warning messages may appear in SYSLOG
(by default
.B /var/log/messages)
about missing block-major-xx devices.  These messages are usually
harmless. Alternatively, the configuration file can be used to exclude
non-existent devices by giving a list of devices to monitor at
start-up.

.SH 
OPTIONS
Long options are not supported on all systems.  Use
.B 'smartd \-h'
to see the available options.
.TP
.B \-d, \-\-debug
Runs 
.B smartd 
in ""debug"" mode. In this mode, it does not 
.B fork
(2) and displays status information to STDOUT.  It also prints more
verbose information about what it is doing.
.TP
.B \-D, \-\-showdirectives
Prints a list (to STDOUT) of all the possible Directives which may
appear in the configuration file /etc/smartd.conf, and then exits.
These Directives are also described later in this man page. They may
appear in the configuration file following the device name.
.TP
.B \-i N, \-\-interval=N
Sets the interval between disk checks to
.I N
seconds, where
.I N
is a decimal integer.  The minimum allowed value is ten and the maximum is the
largest positive integer that can be represented on your system (often 2^31-1).
The default is 1800 seconds.

Note that the superuser can make
.B smartd
check the status of the disks at any time by sending it the 
.B SIGUSR1
signal, for example with the command:
.nf
.B kill -SIGUSR1 <pid>
.fi
where 
.B <pid> 
is the process id number of
.B smartd.
One may also use:
.nf
.B killall -USR1 smartd
.fi
for the same purpose.

.TP
.B \-p NAME, \-\-pidfile=NAME
Writes pidfile
.I NAME
containing the
.B smartd
Process ID number (PID).
To avoid symlink attacks make sure the directory to which
pidfile is written is only writeable for root.  Without this option,
or if the --debug option is given, no PID file is written on startup.
If
.B smartd
is killed with a maskable signal then the pidfile is removed.

.TP
.B \-c, \-\-checkonce
Start
.B smartd
in debug mode, then register devices, then check device's SMART status
once, and then exit with zero exit status if 
all of these steps worked correctly.

This option is intended for 'distribution-writers' who
want to create automated scripts to determine whether or not to
automatically start up
.B smartd
after installing smartmontools.  After starting
.B smartd
with this command-line option, the distribution's install scripts should
wait a reasonable length of time (say ten seconds).  If
.B smartd
has not exited with zero status by that time, the script should send
.B smartd
a SIGTERM or SIGKILL and assume that
.B smartd
will not operate correctly on the host.  Conversely, if
.B smartd
exits with zero status, then it is safe to run
.B smartd
in normal daemon mode.

Note that if
.B smartd
is unable to monitor any devices or encounters other problems then it
will return with non-zero exit status.

.TP
.B \-V, \-\-version, \-\-license, \-\-copyright
Prints license, copyright, and CVS version information onto
STDOUT and then exits. Please include this information if you are
reporting bugs, or have specific questions about the behavior of
.B smartd.
.TP
.B \-h, \-\-help, \-\-usage
Prints usage message to STDOUT and exits.
.TP
.B \-?
Same as
.B -h.


.TP
.B \-r TYPE, \-\-report=TYPE
Intended primarily to help
.B smartmontools
developers understand the behavior of
.B smartmontools
on non-conforming or poorly conforming hardware.  This option reports
details of
.B smartd
transactions with the device.  The option can be used multiple times.
When used just once, it shows a record of the ioctl() transactions
with the device.  Whe used more than once, the detail of these ioctl()
transactions are reported in greater detail.  The valid arguments to
this option are:

.I ioctl
\- report all ioctl() transactions.

.I ataioctl
\- report only ioctl() transactions with ATA devices.

.I scsiioctl
\- report only ioctl() transactions with SCSI devices.

.SH EXAMPLES

.B
smartd
.fi
Runs the daemon in forked mode. This is the normal way to run
.B smartd.
Entries are logged to SYSLOG (by default
.B /var/log/messages.)

.B
smartd -d -i 30
.fi
Run in foreground (debug) mode, checking the disk status
every 30 seconds.

.B
smartd -c
.fi
Registers devices, and checks the status of the devices exactly
once. The exit status (the bash
.B $?
variable) will be zero if all went well, and nonzero if no devices
were detected or some other problem was encountered.

.fi
Note that 
.B smartmontools
provides a start-up script in
.B /etc/rc.d/init.d/smartd
which is responsible for starting and stopping the daemon via the
normal init interface. 
Using this script, you can start
.B smartd
by giving the command:
.nf
.B /etc/rc.d/init.d/smartd start
.fi
and stop it by using the command:
.nf
.B /etc/rc.d/init.d/smartd stop

.fi
If you want
.B smartd
to start running whenever your machine is booted, this can be enabled
by using the command:
.nf
.B /sbin/chkconfig --add smartd
.fi
and disabled using the command:
.nf
.B /sbin/chkconfig --del smartd

\# DO NOT MODIFY THIS OR THE FOLLOWING TWO LINES. THIS MATERIAL
\# IS AUTOMATICALLY INCLUDED IN THE FILE smartd.conf.5
\# STARTINCLUDE

.SH CONFIGURATION FILE /etc/smartd.conf
In the absence of a configuration file,
.B smartd 
will try to open the 12 ATA devices 
.B /dev/hd[a-l] 
and the 26 SCSI devices
.B /dev/sd[a-z]. 
This can be annoying if you have an ATA or SCSI device that hangs or
misbehaves when receiving SMART commands.  Even if this causes no
problems, you may be annoyed by the string of error log messages about
block-major devices that can't be found, and SCSI devices that can't
be opened.

One can avoid this problem, and gain more control over the types of
events monitored by
.B smartd,
by using the configuration file
.B /etc/smartd.conf.
This file contains a list of devices to monitor, with one device per
line.  An example file is included with the
.B smartmontools
distribution, and is normally placed in 
.B /etc/smartd.conf.example.
If
.B smartmontools
was properly installed on your system, you will also find this sample
configuration file in
.B /usr/share/doc/smartmontools-5.1/.
For security, the configuration file should not be writable by anyone
but root. The syntax of the file is as follows:

.IP
There should be one device listed per line, although you may have
lines that are entirely comments or white space.

Any text following a hash sign (#) and up to the end of the line is
taken to be a comment, and ignored.

Lines may be continued by using a backslash (\(rs) as the last
non-whitespace or non-comment item on a line.

.PP 0
.fi
Here is an example configuration file.  It's for illustrative purposes
only; please don't copy it onto your system without reading to the end
of the
.B DIRECTIVES
Section below!

.nf
.B ################################################
.B # This is an example smartd startup config
.B # file /etc/smartd.conf for monitoring three
.B # ATA disks and two SCSI disks.
.B #
.nf
.B # First ATA disk on each of two interfaces:
.B #
.B \ \ /dev/hda -a -m admin@yoyodyne.com,root@localhost 
.B \ \ /dev/hdc -a -I 194 -I 5 -i 12
.B #
.nf
.B # SCSI disks.  Send a TEST warning email to admin on
.B # startup.
.B #
.B \ \ /dev/sda
.B \ \ /dev/sdc -m admin@yoyodyne.com -M test
.B #
.nf
.B # Strange device.  It's SCSI:
.B #
.B \ \ /dev/weird -d scsi
.B #
.nf
.B # The following line enables monitoring of the 
.B # ATA Error Log and the Self-Test Error Log.  
.B # It also tracks changes in both Prefailure
.B # and Usage Attributes, apart from Attributes
.B # 9, 194, and 231, and shows  continued lines:
.B #
.B \ \ /dev/hdd\ -l\ error\ \(rs
.B \ \ \ \ \ \ \ \ \ \ \ -l\ selftest\ \(rs
.B \ \ \ \ \ \ \ \ \ \ \ -t\ \(rs\ \ \ \ \ \ # Attributes not tracked:
.B \ \ \ \ \ \ \ \ \ \ \ -I\ 194\ \(rs\ \ # temperature
.B \ \ \ \ \ \ \ \ \ \ \ -I\ 231\ \(rs\ \ # also temperature
.B \ \ \ \ \ \ \ \ \ \ \ -I 9\ \ \ \ \ \ # power-on hours
.B #
.B ################################################
.fi

.PP 
.SH CONFIGURATION FILE DIRECTIVES
.PP

If the first non-comment entry in the configuration file is the text
string
.B DEVICESCAN
in capital letters, then
.B smartd
will ignore any remaining lines in the configuration file, and will
scan for devices.
.B DEVICESCAN
may optionally be followed by Directives that will apply to all
devices that are found in the scan.  Please see below for additional
details.

.sp 2
The following are the Directives that may appear following the device
name or
.B DEVICESCAN
on any line of the
.B /etc/smartd.conf
configuration file. Note that
.B these are NOT command-line options for 
.B smartd.
The Directives below may appear in any order, following the device
name. 

.B For an ATA device,
if no Directives appear, then the device will be monitored
as if the '\-a' Directive (monitor all SMART properties) had been given.

.B If a SCSI disk is listed,
it will be monitored at the only implemented level: roughly equivalent
to using the '\-H' option for an ATA disk.  So with the exception of '\-d', '\-m', and '\-M',
the Directives below are ignored for SCSI
disks.  For SCSI disks, the '\-m' Directive sends a warning email if
the SMART status indicates a disk failure or problem, or if the SCSI inquiry about disk status fails.

.TP
.B \-d TYPE
Specifies the type of the device.  This will prevent
.B smartd
from issuing SCSI commands to an ATA device and vice versa.  The valid
arguments to this Directive are \fIata\fP and \fIscsi\fP.

In the absence of this Directive,
.B smartd
will first attempt to guess the device type by looking at whether the sixth
character in the device name is an 's' or an 'h'.  This will work for
device names like /dev/hda or /dev/sdb.  If
.B smartd
can't guess from this sixth character, then it will simply try to
access the device using first ATA and then SCSI ioctl()s.
.TP
.B \-T TYPE
Specifies how tolerant
.B smartd
should be of SMART command failures.  The valid arguments to this
Directive are:

.I normal
\- do not try to monitor the disk if a mandatory SMART command fails, but
continue if an optional SMART command fails.  This is the default.

.I permissive
\- try to monitor the disk even if it appears to lack SMART capabilities.
This may be required for some old disks (prior to ATA-3 revision 4) that
implemented SMART before the SMART standards
were incorporated into the ATA/ATAPI Specifications.

[Please see the
.B smartctl \-T
command-line option.]
.TP
.B \-o VALUE
Enables or disables SMART Automatic Offline Testing when
.B smartd
starts up and has no further effect.  The valid arguments to this
Directive are \fIon\fP and \fIoff\fP.

The delay between tests is vendor-specific, but is typically four hours.
[Please see the
.B smartctl \-o
command-line option.]
.TP
.B \-S VALUE
Enables or disables Attribute Autosave when
.B smartd
starts up and has no further effect.  The valid arguments to this
Directive are \fIon\fP and \fIoff\fP.  [Please see the
.B smartctl \-S
command-line option.]
.TP
.B \-H
Check the SMART health status of the disk.  If any Prefailure
Attributes are less than or equal to their threshold values, then disk
failure is predicted in less than 24 hours, and a message at priority
.B 'CRITICAL'
will be logged to syslog.  [Please see the
.B smartctl \-H
command-line option.]
.TP
.B \-l TYPE
Reports increases in the number of errors in one of the two SMART logs.  The
valid arguments to this Directive are:

.I error
\- report if that the number of ATA errors reported in the ATA Error Log has
increased since the last check.

.I selftest
\- report if that the number of errors reported in the SMART Self-Test Log
has increased since the last check.  Note that such errors will
.B only
be logged if you run self-tests on the disk (and it fails the tests!).
[Self-Tests can be run by using the
.B '\-t\ short'
and
.B '\-t\ long'
options of
.B smartctl
and the results of the testing can be observed using the
.B smartctl '\-l\ selftest'
command-line option.]

[Please see the
.B smartctl \-l
command-line option.]
.TP
.B \-f
Check for 'failure' of any Usage Attributes.  If these
Attributes are less than or equal to the threshold, it does NOT
indicate imminent disk failure.  It ""indicates an advisory condition
where the usage or age of the device has exceeded its intended design
life period."" [Please see the
.B smartctl \-A
command-line option.]

.TP
.B \-m ADD
Send a warning email to the email address
.B ADD
if the '\-H', '\-l', or '\-f' Directives detect a failure or a new
error, or is a SMART command to the disk fails. This Directive only
works in conjunction with these other Directives (or with the
equivalent default '\-a' Directive).

To prevent your email in-box from getting filled up with warning
messages, by default only a single warning will be sent for each of
the enabled test types, '\-H', '\-l', or '\-f', even if more than one
failure or error is detected or if the failure or error persists.
[This behavior can be modified; see the '\-M' Directive below.]

To send email to more than one user, please use the following form for
the address:
.B  user1@add1,user2@add2,...,userN@addN
(with no spaces).

To test that email is being sent correctly, use the '\-M test'
Directive described below to send one test email message on
.B smartd
startup.

By default, email is sent using the system 
.B mail
command.  In order that
.B smartd
find the mail command (normally /bin/mail) an executable named
.B 'mail'
must be in the path of the shell or environment from which
.B smartd
was started.  If you wish to specify an explicit path to the mail
executable (for example /usr/local/bin/mail) or a custom script to
run, please use the '\-M exec' Directive below.

Note that there is a special argument
.B <nomailer>
which can be given to the '\-m' Directive in conjunction with the '\-M
exec' Directive. Please see below for an explanation of its effect.

.TP
.B \-M TYPE
These Directives modify the behavior of the
.B smartd
email warnings enabled with the '\-m' email Directive described above.
These '\-M' Directives only work in conjunction with the '\-m'
Directive and can not be used without it.

Multiple \-M Directives may be given.  If conflicting \-M Directives
are given (example: \-M once \-M daily) then the final one (in the
example, \-M daily) is used.

The valid arguments to the \-M Directive are:

.I once
\- send only one warning email for each type of disk problem detected.  This
is the default.

.I daily
\- send additional warning reminder emails, once per day, for each type
of disk problem detected.

.I diminishing
\- send additional warning reminder emails, after a one-day interval,
then a two-day interval, then a four-day interval, and so on for each
type of disk problem detected. Each interval is twice as long as the
previous interval.

.I test
\- send a single test email
immediately upon
.B smartd
startup.  This allows one to verify that any email is correctly delivered.

.I exec PATH
\- run the executable PATH instead of the default mail command, when
.B smartd
needs to send email.  PATH must point to an executable binary file or
script.

By setting PATH to point to a customized script, you can make
.B smartd
perform useful tricks when a disk problem is detected (beeping the
console, shutting down the machine, broadcasting warnings to all
logged-in users, etc.)  But please be careful.
.B smartd
will
.B block
until the executable PATH returns, so if your executable hangs, then
.B smartd
will also hang.  Some sample scripts are included in
/usr/share/doc/smartmontools-5.1/examplescripts/.

The return status of the executable is recorded by
.B smartd
in SYSLOG, but the executable's STDOUT and STDERR are directed to
/dev/null, so if you wish to leave some other record behind, the
executable must send mail or write to a file or device.

Before running the executable,
.B smartd
sets a number of environment variables.  These environment variables
may be used to control the executable's behavior.  The environment
variables exported by
.B smartd
are:
.nf
.fi
.B SMARTD_MAILER
is set to the argument of -M exec, if present or else to 'mail'
(examples: /bin/mail, mail).
.nf
.fi
.B SMARTD_DEVICE
is set to the device path (examples: /dev/hda, /dev/sdb).
.nf
.fi
.B SMARTD_DEVICETYPE
is set to the device type (possible values: ata, scsi).
.nf
.fi
.B SMARTD_FAILTYPE
gives the reason for the warning or message email.  The possible values that
it takes, and their significance, are:
.I emailtest
(this is an email test message);
.I health
(the SMART health status indicates imminent failure);
.I usage
(a usage Attribute has failed);
.I selftest
(the number of self-test failures has increased);
.I errorcount
(the number of errors in the ATA error log has increased);
.I FAILEDhealthcheck
(the SMART health status command failed);
.I FAILEDreadsmartdata
(the command to read SMART Attribute data failed);
.I FAILEDreadsmarterrorlog
(the command to read the SMART error log failed);
.I FAILEDreadsmartsefltestlog
(the command to read the SMART self-test log failed); abd
.I FAILEDopendevice
(the open() command to the device failed).
.nf
.fi
.B SMARTD_ADDRESS
is set to the address argument ADD of the '\-m' Directive, unless ADD
is
.B <nomailer>.
This is a comma-delineated list of email addresses (example:
admin@yoyodyne.com).
.nf
.fi
.B SMARTD_MESSAGE
is set to the warning email message string from
.B smartd. 
This message string contains space characters and is NOT quoted. So to
use $SMARTD_MESSAGE in a bash script you should probably enclose it in
double quotes.
.nf
.fi
.B SMARTD_TFIRST
is a text string giving the time and date at which the first problem
of this type was reported. This text string contains space characters
and no newlines, and is NOT quoted. For example:
.nf
.fi
Sun Feb  9 14:58:19 2003 CST
.nf
.fi
.B SMARTD_TFIRSTEPOCH
is an integer, which is the unix epoch (number of seconds since Jan 1,
1970) for
.B SMARTD_TFIRST.

The shell which is used to run PATH is system-dependent. For vanilla
linux/glibc it's bash. For other systems, the man page for system (3)
should say what shell is used.

If the '\-m ADD' Directive is given with a normal address argument,
then the executable pointed to by PATH will be run in a shell with
STDIN receiving the body of the email message, and with the same
command-line arguments:
.nf
-s \(dq$SMARTD_SUBJECT\(dq $SMARTD_ADDRESS
.fi
that would normally be provided to 'mail'.  Examples include:
.nf
.B -m user@home -M exec /bin/mail
.B -m admin@work -M exec /usr/local/bin/mailto
.B -m root -M exec /Example_1/bash/script/below
.fi

If the '\-m ADD' Directive is given with the special address argument
.B <nomailer>
then the executable pointed to by PATH is run in a shell with
.B no
STDIN and
.B no
command-line arguments, for example:
.nf
.B -m <nomailer> -M exec /Example_2/bash/script/below
.fi

Some EXAMPLES of scripts that can be used with the '\-M exec'
Directive are given below. Some sample scripts are also included in
/usr/share/doc/smartmontools-5.1/examplescripts/.

.TP
.B \-p
Report anytime that a Prefail Attribute has changed
its value since the last check, 30 minutes ago. [Please see the
.B smartctl \-A
command-line option.]
.TP
.B \-u
Report anytime that a Usage Attribute has changed its value
since the last check, 30 minutes ago. [Please see the
.B smartctl \-A
command-line option.]
.TP
.B \-t
Equivalent to turning on the two previous flags '\-p' and '\-u'.
Tracks changes in
.I all
device Attributes (both Prefailure and Usage). [Please see the
.B smartctl \-A
command-line option.]
.TP
.B \-i ID
Ignore device Attribute number
.B ID
when checking for failure of Usage Attributes.
.B ID
must be a decimal integer in the range from 1 to 255.  This Directive
modifies the behavior of the '\-f' Directive and has no effect without
it.

This is useful, for example, if you have a very old disk and don't want to keep
getting messages about the hours-on-lifetime Attribute (usually Attribute 9)
failing.  This Directive may appear multiple times for a single device, if you
want to ignore multiple Attributes.
.TP
.B \-I ID
Ignore device Attribute
.B ID
when tracking changes in the Attribute values.
.B ID
must be a decimal integer in the range from 1 to 255.  This Directive modifies
the behavior of the '\-p', '\-u', and '\-t' tracking Directives and has no effect
without one of them.

This is useful, for example, if one of the device Attributes is the disk
temperature (usually Attribute 194 or 231). It's annoying to get reports
each time the temperature changes.  This Directive may appear multiple
times for a single device, if you want to ignore multiple Attributes.
.TP
.B \-r ID
When tracking, report the
.I Raw
value of Attribute
.B ID
along with its (normally reported)
.I Normalized
value.
.B ID
must be a decimal integer in the range from 1 to 255.  This Directive modifies
the behavior of the '\-p', '\-u', and '\-t' tracking Directives and has no effect
without one of them.  This Directive may be given multiple times.

A common use of this Directive is to track the device Temperature
(often ID=194 or 231).

.TP
.B \-R ID
When tracking,
report whenever the
.I Raw
value of Attribute
.B ID
changes.  (Normally
.B smartd
only tracks/reports changes of the
.I Normalized
Attribute values.)
.B ID
must be a decimal integer in the range from 1 to 255.  This Directive
modifies the behavior of the '\-p', '\-u', and '\-t' tracking Directives and
has no effect without one of them.  This Directive may be given
multiple times.

If this Directive is given, it automatically implies the '\-r'
Directive for the same Attribute, so that the Raw value of the
Attribute is reported.

A common use of this Directive is to track the device Temperature
(often ID=194 or 231).  It is also useful for understanding how
different types of system behavior affects the values of certain
Attributes.

.TP
.B \-F
In some Samsung disks (example: model SV4012H Firmware Version:
RM100-08) some of the two- and four-byte quantities in the SMART data
structures are byte-swapped (relative to the ATA specification).
Enabling this option tells smartmontools to evaluate these quantities
in byte-reversed order.

Some signs that your disk needs this option are (1) no self-test log
printed, even though you have run self-tests; (2) very large numbers
of ATA errors reported in the ATA erorr log; (3) strange and
impossible values for the ATA error log timestamps.

[Please see the
.B smartctl \-F
command-line option.]

.TP
.B \-v N,OPTION
Modifies the labeling for Attribute N, for disks which use
non-standard Attribute definitions.  This is useful in connection with
the Attribute tracking/reporting Directives.

This Directive may appear multiple times. Valid arguments to this
Directive are:

.I 9,minutes
\- Raw Attribute number 9 is power-on time in minutes.  Its raw value
will be displayed in the form 'Xh+Ym'.  Here X is hours, and Y is
minutes in the range 0-59 inclusive.  Y is always printed with two
digits, for example \'06' or \'31' or '00'.

.I 9,seconds
\- Raw Attribute number 9 is power-on time in seconds.  Its raw value
will be displayed in the form 'Xh+Ym+Zs'.  Here X is hours, Y is
minutes in the range 0-59 inclusive, and Z is seconds in the range
0-59 inclusive.  Y and Z are always printed with two digits, for
example \'06' or \'31' or '00'.

.I 9,halfminutes
\- Raw Attribute number 9 is power-on time, measured in units of 30
seconds.  This format is used by some Samsung disks.  Its raw value
will be displayed in the form 'Xh+Ym'.  Here X is hours, and Y is
minutes in the range 0-59 inclusive.  Y is always printed with two
digits, for example \'06' or \'31' or '00'.

.I 9,temp
\- Raw Attribute number 9 is the disk temperature in Celsius.

.I 194,10xCelsius
\- Raw Attribute number 194 is ten times the disk temperature in
Celsius.  This is used by some Samsung disks (example: model SV1204H
with RK100-13 firmware).

.I 200,writeerrorcount
\- Raw Attribute number 200 is the Write Error Count.

.I 220,temp
\- Raw Attribute number 220 is the disk temperature in Celsius.

Note: a table of hard drive models, listing which Attribute
corresponds to temperature, can be found at:
http://coredump.free.fr/linux/hddtemp.db

.I N,raw8
\- Print the Raw value of Attribute N as six 8-bit unsigned base-10
integers.  This may be useful for decoding the meaning of the Raw
value.  The form 'N,raw8' prints Raw values for ALL Attributes in this
form.  The form (for example) '123,raw8' only prints the Raw value for
Attribute 123 in this form.

.I N,raw16
\- Print the Raw value of Attribute N as three 16-bit unsigned base-10
integers.  This may be useful for decoding the meaning of the Raw
value.  The form 'N,raw16' prints Raw values for ALL Attributes in this
form.  The form (for example) '123,raw16' only prints the Raw value for
Attribute 123 in this form.

.I N,raw48
\- Print the Raw value of Attribute N as a 48-bit unsigned base-10
integer.  This may be useful for decoding the meaning of the Raw
value.  The form 'N,raw48' prints Raw values for ALL Attributes in
this form.  The form (for example) '123,raw48' only prints the Raw
value for Attribute 123 in this form.

.TP
.B \-a
Equivalent to turning on all of the following Directives: 
.B '\-H' 
to check the SMART health status,
.B '\-f' 
to report failures of Usage (rather than Prefail) Attributes,
.B '\-t' 
to track changes in both Prefailure and Usage Attributes,
.B '\-l\ selftest' 
to report increases in the number of Self-Test Log errors, and
.B '\-l\ error' 
to report increases in the number of ATA errors.

Note that \-a is the default for ATA devices.  If none of these other
Directives is given, then \-a is assumed.

.TP
.B #
Comment: ignore the remainder of the line.
.TP
.B \(rs
Continuation character: if this is the last non-white or non-comment
character on a line, then the following line is a continuation of the current
one.
.PP
If you are not sure which Directives to use, I suggest experimenting
for a few minutes with
.B smartctl
to see what SMART functionality your disk(s) support(s).  If you do
not like voluminous syslog messages, a good choice of
.B smartd
configuration file Directives might be:
.nf
.B \-H \-l\ selftest \-l\ error \-f.
.fi
If you want more frequent information, use:
.B -a.

.TP
.B ADDITIONAL DETAILS ABOUT DEVICESCAN
If the first non-comment entry in the configuration file is the text
string
.B DEVICESCAN
in capital letters, then
.B smartd
will ignore any remaining lines in the configuration file, and will
scan for devices.

If
.B DEVICESCAN 
is not followed by any Directives, then smartd will scan for both ATA
and SCSI devices, and will monitor all possible SMART properties of
any devices that are found.

.B DEVICESCAN
may optionally be followed by any valid Directives, which will be
applied to all devices that are found in the scan.  For example
.nf
.B DEVICESCAN -m root@yoyodyne.com
.fi
will scan for all devices, and then monitor them.  It will send one
email warning per device for any problems that are found.
.nf
.B  DEVICESCAN -d ata -m root@yoyodyne.com
.fi
will do the same, but restricts the scan to ATA devices only.  
.nf
.B  DEVICESCAN -H -d ata -m root@yoyodyne.com
.fi
will do the same, but only monitors the SMART health status of the
devices, (rather than the default \-a, which monitors all SMART
properties).

.TP
.B EXAMPLES OF SHELL SCRIPTS FOR '\-M exec'
These are two examples of shell scripts that can be used with the '\-M
exec PATH' Directive described previously.  The paths to these scripts
and similar executables is the PATH argument to the '\-M exec PATH'
Directive.

Example 1: This script is for use with '\-m ADDRESS -M exec PATH'.  It appends
the output of
.B smartctl -a
to the output of the smartd email warning message and sends it to ADDRESS.

.nf
.B #! /bin/bash

.B # Save the email message (STDIN) to a file:
.B cat > /root/msg
 
.B # Append the output of smartctl -a to the message:
.B /usr/sbin/smartctl -a $SMARTD_DEVICE >> /root/msg
 
.B # Now email the message to the user at address ADD:
.B /bin/mail -s \(dq$SMARTD_SUBJECT\(dq $SMARTD_ADDRESS < /root/msg
.fi

Example 2: This script is for use with '\-m <nomailer> \-M exec
PATH'. It warns all users about a disk problem, waits 30 seconds, and
then powers down the machine.

.nf
.B #! /bin/bash

.B # Warn all users of a problem
.B wall 'Problem detected with disk: ' $SMARTD_DEVICE
.B wall 'Warning message from smartd is: ' \(dq$SMARTD_MESSAGE\(dq
.B wall 'Shutting down machine in 30 seconds... '
 
.B # Wait half a minute
.B sleep 30
 
.B # Power down the machine
.B /usr/sbin/shutdown -hf now
.fi

Some example scripts are distributed with the smartmontools package,
in /usr/share/doc/smartmontools-5.1/examplescripts/.

Please note that these scripts typically run as root, so any files
that they read/write should not be writable by ordinary users or
reside in directories like /tmp that are writable by ordinary users
and may expose your system to symlink attacks.

\# ENDINCLUDE
\# DO NOT MODIFY THIS OR PREVIOUS/NEXT LINES. THIS DEFINES THE 
\# END OF THE INCLUDE SECTION FOR smartd.conf.5

.SH NOTES
.B smartd
will make log entries at loglevel 
.B LOG_INFO
if the Normalized SMART Attribute values have changed, as reported using the
.B '\-t', '\-p',
or
.B '\-u'
Directives. For example:
.nf
.B 'Device: /dev/hda, SMART Attribute: 194 Temperature_Celsius changed from 94 to 93'
.fi
Note that in this message, the value given is the 'Normalized' not the 'Raw' 
Attribute value (the disk temperature in this case is about 22
Celsius).  The 
.B '-R'
and 
.B '-r'
Directives modify this behavior, so that the information is printed
with the Raw values as well, for example:
.nf
.B 'Device: /dev/hda, SMART Attribute: 194 Temperature_Celsius changed from 94 [Raw 22] to 93 [Raw 23]'
.fi
Here the Raw values are the actual disk temperatures in Celsius.  The
way in which the Raw values are printed, and the names under which the
Attributes are reported, is governed by the various
.B \'-v Num,Description'
Directives described previously.

Please see the
.B smartctl
manual page for further explanation of the differences between
Normalized and Raw Attribute values.

.B smartd
will make log entries at loglevel
.B LOG_CRIT
if a SMART Attribute has failed, for example:
.nf
.B 'Device: /dev/hdc, Failed SMART Attribute: 5 Reallocated_Sector_Ct'
.fi
 This loglevel is used for reporting enabled by the
.B '\-H', \-f', '\-l\ selftest',
and
.B '\-l\ error'
Directives. Entries reporting failure of SMART Prefailure Attributes
should not be ignored: they mean that the disk is failing.  Use the
.B smartctl
utility to investigate. 

.PP
.SH AUTHOR
Bruce Allen
.B smartmontools-support@lists.sourceforge.net
.fi
University of Wisconsin - Milwaukee Physics Department

.PP
.SH CREDITS
.fi
This code was derived from the smartsuite package, written by Michael
Cornwell, and from the previous ucsc smartsuite package. It extends
these to cover ATA-5 disks. This code was originally developed as a
Senior Thesis by Michael Cornwell at the Concurrent Systems Laboratory
(now part of the Storage Systems Research Center), Jack Baskin School
of Engineering, University of California, Santa
Cruz. http://ssrc.soe.ucsc.edu/.
.SH
HOME PAGE FOR SMARTMONTOOLS: 
.fi
Please see the following web site for updates, further documentation, bug
reports and patches:
.nf
.B
http://smartmontools.sourceforge.net/

.SH
SEE ALSO:
.B smartd.conf
(5),
.B smartctl
(8),
.B syslogd
(8)
.SH
REFERENCES FOR S.M.A.R.T.
.fi
If you would like to understand better how S.M.A.R.T. works, and what
it does, a good place to start is  Section 8.41 of the 'AT
Attachment with Packet Interface-5' (ATA/ATAPI-5) specification.  This
documents the S.M.A.R.T. functionality which the 
.B smartmontools
utilities provide access to.  You can find Revision 1 of this document
at:
.nf
.B
http://www.t13.org/project/d1321r1c.pdf
.fi
Future versions of the specifications (ATA/ATAPI-6 and ATA/ATAPI-7),
and later revisions (2, 3) of the ATA/ATAPI-5 specification are
available from:
.nf
.B
http://www.t13.org/#FTP_site

.fi
The functioning of S.M.A.R.T. is also described by the SFF-8035i
revision 2 specification.  This is a publication of the Small Form
Factors (SFF) Committee, and can be obtained from:
.TP
\ 
SFF Committee
.nf
14426 Black Walnut Ct.
.nf
Saratoga, CA 95070, USA
.nf
SFF FaxAccess: +01 408-741-1600
.nf
Ph: +01 408-867-6630
.nf
Fax: +01 408-867-2115
.nf
E-Mail: 250-1752@mcimail.com.
.PP
Please let us know if there is an on\-line source for this document.

.SH
CVS ID OF THIS PAGE:
$Id: smartd.8,v 1.83 2003/04/10 09:40:36 ballen4705 Exp $
