/* config.h for MSVC6, NOT Generated by configure.  */

/* smartmontools CVS Tag */
#define CONFIG_H_CVSID "$Id: config_vc6.h,v 1.2 2004/03/12 23:29:06 chrfranke Exp $"

/* use mailx as default mailer */
/* #undef DEFAULT_MAILER */

/* Define to 1 if you have the <dev/ata/atavar.h> header file. */
/* #undef HAVE_DEV_ATA_ATAVAR_H */

/* Define to 1 if you have the `getdomainname' function. */
#undef HAVE_GETDOMAINNAME

/* Define to 1 if you have the `getopt' function. */
#undef HAVE_GETOPT

/* Define to 1 if you have the `getopt_long' function. */
#define HAVE_GETOPT_LONG 1

/* Define to 1 if you have the <inttypes.h> header file. */
#undef HAVE_INTTYPES_H

/* Define to 1 if you have the <linux/hdreg.h> header file. */
/* #undef HAVE_LINUX_HDREG_H */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `sigset' function. */
#undef HAVE_SIGSET

/* Define to 1 if you have the <stdint.h> header file. */
#undef HAVE_STDINT_H

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#undef HAVE_STRINGS_H

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the `uname' function. */
#undef HAVE_UNAME

/* Define to 1 if you have the <unistd.h> header file. */
#undef HAVE_UNISTD_H

/* need assembly code os_solaris_ata.s */
/* #undef NEED_SOLARIS_ATA_CODE */

/* Name of package */
#define PACKAGE "smartmontools"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "smartmontools-support@lists.sourceforge.net"

/* smartmontools Home Page */
#define PACKAGE_HOMEPAGE "http://smartmontools.sourceforge.net/"

/* Define to the full name of this package. */
#define PACKAGE_NAME "smartmontools"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "smartmontools "PACKAGE_VERSION

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "smartmontools"

/* Define to the version of this package. */
#define PACKAGE_VERSION VERSION

/* smartmontools Build Host */
#define SMARTMONTOOLS_BUILD_HOST "i686-pc-win32"

/* smartmontools Configure Arguments */
#define SMARTMONTOOLS_CONFIGURE_ARGS ""

/* smartmontools Configure Date */
#define SMARTMONTOOLS_CONFIGURE_DATE "2004/03/12 18:42:00 UTC"

/* smartmontools Release Date */
#define SMARTMONTOOLS_RELEASE_DATE "2004/03/07"

/* smartmontools Release Time */
#define SMARTMONTOOLS_RELEASE_TIME "20:57:36 UTC"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "5.31"
