#! /bin/sh
#
# This is a script from the smartmontools examplescripts/ directory.
# It can be used as an argument to the -M exec Directive in
# /etc/smartd.conf, in a line like
# ... -m root@localhost -M exec /path/to/this/file
#
# See also: smartd.conf(5), smartd(8).
#
# $Id$

if [ $# -le 3 ] || [ "$1" != "-s" ]; then
  echo "Usage: $0 -s SUBJECT ADDRESS... < MESSAGE"
  exit 1
fi

SUBJECT=$2
shift; shift
ADDRESS=$*

exec /usr/sbin/sendmail $ADDRESS <<EOF
Subject: $SUBJECT
To: $(echo $ADDRESS | sed 's/ /, /g')

$(cat -)
EOF
