name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/smartmontools/docker-build:master

    steps:
    - uses: actions/checkout@v4
    - name: Set SOURCE_DATE_EPOCH
      run: |
        echo "SOURCE_DATE_EPOCH=$s # `date -d @"$s" -u -Is`" &&
        echo "$s" >~/SOURCE_DATE_EPOCH
    - name: Creating src.tar.gz
      run: | 
        ./autogen.sh && ./configure
