name: Build smartmontools (non-release)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  make-src-tgz:
    runs-on: ubuntu-latest
    outputs:
      SOURCE_DATE_EPOCH: ${{ steps.set-env.outputs.SOURCE_DATE_EPOCH }}
      SM_VER: ${{ steps.set-env.outputs.SM_VER }}
      SM_REV: ${{ steps.set-env.outputs.SM_REV }}

    # container: 
    #   image: ghcr.io/smartmontools/docker-build:master

    steps:
    - uses: actions/checkout@v4
    - name: Setting environment variables
      id: set-env
      run: |
        git log -1 --format="SOURCE_DATE_EPOCH=%at" >> $GITHUB_ENV
        echo SM_VER=$(sed -n 's|^AC_INIT[^,]*, *\[\([0-9.]*\)\] *,.*$|\1|p' configure.ac) >> $GITHUB_ENV
        echo SM_REV=$(git rev-parse --short=12 HEAD) >> $GITHUB_ENV
        cat $GITHUB_ENV | tee $GITHUB_OUTPUT

    - name: Creating src.tar.gz
      run: |
        ./autogen.sh --force 
        mkdir build && cd build
        ../configure SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}
        make dist && tar -tvzf smartmontools-${SM_VER}.tar.gz
        mkdir artifacts
        echo ${SOURCE_DATE_EPOCH} > artifacts/SOURCE_DATE_EPOCH
        mv smartmontools-${SM_VER}.tar.gz artifacts/

    - name: Upload distfile
      uses: actions/upload-artifact@v4
      with:
        name: smartmontools-${SM_VER}.tar.gz
        path: build/artifacts/smartmontools-${SM_VER}.tar.gz

  compile-linux:
    needs: make-src-tgz
    runs-on: ubuntu-latest
    env:
      SOURCE_DATE_EPOCH: ${{ needs.make-src-tgz.outputs.SOURCE_DATE_EPOCH }}
      SM_VER: ${{ needs.make-src-tgz.outputs.SM_VER }}
      SM_REV: ${{ needs.make-src-tgz.outputs.SM_REV }}      
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: smartmontools-${SM_VER}.tar.gz
      - name: build
        run: |
          tar -xvf smartmontools-${SM_VER}.tar.gz
          ls
