name: Build smartmontools on QEMU

on:
  workflow_dispatch:
    inputs:
      native-platforms:
        description: >-
          Native platforms or 'none' (defaults to all)
        required: false
        default: >-
          freebsd-x86_64 netbsd-x86_64 openbsd openindiana solaris
      emulated-le-platforms:
        description: >-
          Emulated Little Endian platforms (slow):
          freebsd-arm64 ubuntu-riscv64
        required: false
        default: none
      emulated-be-platforms:
        description: >-
          Emulated Big Endian platforms (slow):
          freebsd-powerpc64 netbsd-sparc64 ubuntu-s390x
        required: false
        default: none

jobs:
  build-source-tarball:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          # Provide at least the commit log since last release for 'getversion.sh'.
          # 'git clone --shallow-since=2025-04-29' would be sufficient but this is
          # not supported by 'actions/checkout@v6'.
          fetch-depth: 800
          # Include (future) release tags for 'getversion.sh'
          fetch-tags: true

      - name: Build
        run: |
          version_sh=$(src/getversion.sh -s) && eval "${version_sh}" &&
          ./autogen.sh && mkdir build && cd build &&
          ../configure SOURCE_DATE_EPOCH=$((SMARTMONTOOLS_GIT_REV_EPOCH + 1)) &&
          make dist &&
          mv -v "smartmontools-${SMARTMONTOOLS_PKG_VER}.tar.gz" \
                "smartmontools-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz" &&
          tar -tvf "smartmontools-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz"

      - uses: actions/upload-artifact@v7
        with:
          name: smartmontools-src
          path: build/smartmontools-*.tar.gz
          retention-days: 90

  build-freebsd-x86_64:
    if: ${{ contains(github.event.inputs.native-platforms, 'freebsd-x86_64') }}
    needs: build-source-tarball
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: smartmontools-src

      - name: Build and Run (QEMU)
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true # use 'sh' instead of 'tcsh'
          run: | # SOURCE_DATE_EPOCH not used because GNU tar is not installed by default
            uname -a && ver=$(uname -r) && ver=${ver%%.*} &&
            distfile=$(ls -d smartmontools-*.tar.gz) &&
            test "$(echo "$distfile" | wc -l | tr -d ' ')" = 1 &&
            tar -xf "$distfile" && distdir=${distfile%-*-g*.tar.gz} &&
            version_sh=$("$distdir/src/getversion.sh" -s) && eval "${version_sh}" &&
            cd smartmontools-${SMARTMONTOOLS_PKG_VER} && mkdir build && cd build &&
            ../configure --with-build-info='(GHA/qemu)' &&
            make -j4 && make check &&
            bin_distfile="../../smartmontools-freebsd-$ver-x86_64-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz" &&
            make bin_distfile="$bin_distfile" bin-dist && tar -tvf "$bin_distfile" &&
            tar -xf "$bin_distfile" usr/local/sbin/smartctl &&
            echo '$' usr/local/sbin/smartctl --scan &&
            { usr/local/sbin/smartctl --scan || echo "::error::'smartctl --scan' failed"; }

      - uses: actions/upload-artifact@v7
        with:
          name: smartmontools-freebsd-x86_64
          path: smartmontools-freebsd-*.tar.gz
          retention-days: 90

  build-freebsd-arm64:
    if: ${{ contains(github.event.inputs.emulated-le-platforms, 'freebsd-arm64') }}
    needs: build-source-tarball
    runs-on: ubuntu-latest # 'ubuntu-24.04-arm' is slower
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: smartmontools-src

      - name: Build and Run (QEMU)
        uses: vmactions/freebsd-vm@v1
        with:
          arch: aarch64
          usesh: true # use 'sh' instead of 'tcsh'
          run: | # SOURCE_DATE_EPOCH not used because GNU tar is not installed by default
            uname -a && ver=$(uname -r) && ver=${ver%%.*} &&
            distfile=$(ls -d smartmontools-*.tar.gz) &&
            test "$(echo "$distfile" | wc -l | tr -d ' ')" = 1 &&
            tar -xf "$distfile" && distdir=${distfile%-*-g*.tar.gz} &&
            version_sh=$("$distdir/src/getversion.sh" -s) && eval "${version_sh}" &&
            cd smartmontools-${SMARTMONTOOLS_PKG_VER} && mkdir build && cd build &&
            ../configure --with-build-info='(GHA/x86_64)' &&
            make -j4 && make check &&
            bin_distfile="../../smartmontools-freebsd-$ver-arm64-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz" &&
            make bin_distfile="$bin_distfile" bin-dist && tar -tvf "$bin_distfile" &&
            tar -xf "$bin_distfile" usr/local/sbin/smartctl &&
            echo '$' usr/local/sbin/smartctl --scan &&
            { usr/local/sbin/smartctl --scan || echo "::error::'smartctl --scan' failed"; }

      - uses: actions/upload-artifact@v7
        with:
          name: smartmontools-freebsd-arm64
          path: smartmontools-freebsd-*.tar.gz
          retention-days: 90

  build-freebsd-powerpc64: # Big Endian
    if: ${{ contains(github.event.inputs.emulated-be-platforms, 'freebsd-powerpc64') }}
    needs: build-source-tarball
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: smartmontools-src

      - name: Build and Run (QEMU)
        uses: vmactions/freebsd-vm@v1
        with:
          arch: powerpc64
          sync: scp # 'rsync' not supported
          usesh: true # use 'sh' instead of 'tcsh'
          run: | # SOURCE_DATE_EPOCH not used because GNU tar is not installed by default
            uname -a && ver=$(uname -r) && ver=${ver%%.*} &&
            distfile=$(ls -d smartmontools-*.tar.gz) &&
            test "$(echo "$distfile" | wc -l | tr -d ' ')" = 1 &&
            tar -xf "$distfile" && distdir=${distfile%-*-g*.tar.gz} &&
            version_sh=$("$distdir/src/getversion.sh" -s) && eval "${version_sh}" &&
            cd smartmontools-${SMARTMONTOOLS_PKG_VER} && mkdir build && cd build &&
            ../configure --with-build-info='(GHA/x86_64)' &&
            make -j4 && make check &&
            bin_distfile="../../smartmontools-freebsd-$ver-powerpc64-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz" &&
            make bin_distfile="$bin_distfile" bin-dist && tar -tvf "$bin_distfile" &&
            tar -xf "$bin_distfile" usr/local/sbin/smartctl &&
            echo '$' usr/local/sbin/smartctl --scan &&
            { usr/local/sbin/smartctl --scan || echo "::error::'smartctl --scan' failed"; }

      - uses: actions/upload-artifact@v7
        with:
          name: smartmontools-freebsd-powerpc64
          path: smartmontools-freebsd-*.tar.gz
          retention-days: 90

  build-netbsd-x86_64:
    if: ${{ contains(github.event.inputs.native-platforms, 'netbsd-x86_64') }}
    needs: build-source-tarball
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: smartmontools-src

      - name: Build and Run (QEMU)
        uses: vmactions/netbsd-vm@v1
        with:
          usesh: true
          run: | # SOURCE_DATE_EPOCH not used because GNU tar is not installed by default
            uname -a && ver=$(uname -r) && ver=${ver%%.*} &&
            distfile=$(ls -d smartmontools-*.tar.gz) &&
            test "$(echo "$distfile" | wc -l | tr -d ' ')" = 1 &&
            tar -xf "$distfile" && distdir=${distfile%-*-g*.tar.gz} &&
            version_sh=$("$distdir/src/getversion.sh" -s) && eval "${version_sh}" &&
            cd smartmontools-${SMARTMONTOOLS_PKG_VER} && mkdir build && cd build &&
            ../configure --with-build-info='(GHA/qemu)' &&
            make -j4 && make check &&
            bin_distfile="../../smartmontools-netbsd-$ver-x86_64-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz" &&
            make bin_distfile="$bin_distfile" bin-dist && tar -tvf "$bin_distfile" &&
            tar -xf "$bin_distfile" usr/local/sbin/smartctl &&
            echo '$' usr/local/sbin/smartctl --scan &&
            { usr/local/sbin/smartctl --scan || echo "::error::'smartctl --scan' failed"; }

      - uses: actions/upload-artifact@v7
        with:
          name: smartmontools-netbsd-x86_64
          path: smartmontools-netbsd-*.tar.gz
          retention-days: 90

  build-netbsd-sparc64: # Big Endian
    if: ${{ contains(github.event.inputs.emulated-be-platforms, 'netbsd-sparc64') }}
    needs: build-source-tarball
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: smartmontools-src

      - name: Build and Run (QEMU)
        uses: vmactions/netbsd-vm@v1
        with:
          arch: sparc64
          sync: scp # 'rsync' not supported in release 11.0
          usesh: true
          run: | # SOURCE_DATE_EPOCH not used because GNU tar is not installed by default
            uname -a && ver=$(uname -r) && ver=${ver%%.*} &&
            distfile=$(ls -d smartmontools-*.tar.gz) &&
            test "$(echo "$distfile" | wc -l | tr -d ' ')" = 1 &&
            tar -xf "$distfile" && distdir=${distfile%-*-g*.tar.gz} &&
            version_sh=$("$distdir/src/getversion.sh" -s) && eval "${version_sh}" &&
            cd smartmontools-${SMARTMONTOOLS_PKG_VER} && mkdir build && cd build &&
            ../configure --with-build-info='(GHA/qemu)' &&
            make -j4 && make check &&
            bin_distfile="../../smartmontools-netbsd-$ver-sparc64-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz" &&
            make bin_distfile="$bin_distfile" bin-dist && tar -tvf "$bin_distfile" &&
            tar -xf "$bin_distfile" usr/local/sbin/smartctl &&
            echo '$' usr/local/sbin/smartctl --scan &&
            { usr/local/sbin/smartctl --scan || echo "::error::'smartctl --scan' failed"; }

      - uses: actions/upload-artifact@v7
        with:
          name: smartmontools-netbsd-sparc64
          path: smartmontools-netbsd-*.tar.gz
          retention-days: 90

  build-openbsd-x86_64:
    if: ${{ contains(github.event.inputs.native-platforms, 'openbsd') }}
    needs: build-source-tarball
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: smartmontools-src

      - name: Build and Run (QEMU)
        uses: vmactions/openbsd-vm@v1
        with:
          usesh: true
          run: | # SOURCE_DATE_EPOCH not used because GNU tar is not installed by default
            uname -a && ver=$(uname -r) && ver=${ver%%.*} &&
            distfile=$(ls -d smartmontools-*.tar.gz) &&
            test "$(echo "$distfile" | wc -l | tr -d ' ')" = 1 &&
            tar -xzf "$distfile" && distdir=${distfile%-*-g*.tar.gz} &&
            version_sh=$("$distdir/src/getversion.sh" -s) && eval "${version_sh}" &&
            cd smartmontools-${SMARTMONTOOLS_PKG_VER} && mkdir build && cd build &&
            ../configure --with-build-info='(GHA/qemu)' &&
            make -j4 && make check &&
            bin_distfile="../../smartmontools-openbsd-$ver-x86_64-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz" &&
            make bin_distfile="$bin_distfile" bin-dist && tar -tvzf "$bin_distfile" &&
            tar -xzf "$bin_distfile" usr/local/sbin/smartctl &&
            echo '$' usr/local/sbin/smartctl --scan &&
            { usr/local/sbin/smartctl --scan || echo "::error::'smartctl --scan' failed"; }

      - uses: actions/upload-artifact@v7
        with:
          name: smartmontools-openbsd-x86_64
          path: smartmontools-openbsd-*.tar.gz
          retention-days: 90

  build-openindiana-x86_64:
    if: ${{ contains(github.event.inputs.native-platforms, 'openindiana') }}
    needs: build-source-tarball
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: smartmontools-src

      - name: Build and Run (QEMU)
        uses: vmactions/openindiana-vm@v1
        with:
          release: "202604-build" # "202604" + "pkg install build-essential"
          usesh: true
          run: |
            uname -a && ver=$(uname -r) && ver=${ver%%.*} &&
            distfile=$(ls -d smartmontools-*.tar.gz) &&
            test "$(echo "$distfile" | wc -l | tr -d ' ')" = 1 &&
            tar -xf "$distfile" && distdir=${distfile%-*-g*.tar.gz} &&
            version_sh=$("$distdir/src/getversion.sh" -s) && eval "${version_sh}" &&
            cd smartmontools-${SMARTMONTOOLS_PKG_VER} && mkdir build && cd build &&
            ../configure --with-build-info='(GHA/qemu)' \
              MAKE=gmake OBJCOPY=gobjcopy \
              SOURCE_DATE_EPOCH=$((SMARTMONTOOLS_GIT_REV_EPOCH + 1)) &&
            gmake -j4 && gmake check &&
            bin_distfile="../../smartmontools-openindiana-$ver-x86_64-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz" &&
            gmake bin_distfile="$bin_distfile" bin-dist && tar -tvf "$bin_distfile" &&
            tar -xf "$bin_distfile" usr/local/sbin/smartctl &&
            echo '$' usr/local/sbin/smartctl --scan &&
            { usr/local/sbin/smartctl --scan || echo "::error::'smartctl --scan' failed"; }

      - uses: actions/upload-artifact@v7
        with:
          name: smartmontools-openindiana-x86_64
          path: smartmontools-openindiana-*.tar.gz
          retention-days: 90

  build-solaris-x86_64:
    if: ${{ contains(github.event.inputs.native-platforms, 'solaris') }}
    needs: build-source-tarball
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: smartmontools-src

      - name: Build and Run (QEMU)
        uses: vmactions/solaris-vm@v1
        with:
          release: "11.4-gcc" # CBE with default gcc/g++
          usesh: true
          run: |
            uname -a && ver=$(uname -r) && ver=${ver%%.*} &&
            distfile=$(ls -d smartmontools-*.tar.gz) &&
            test "$(echo "$distfile" | wc -l | tr -d ' ')" = 1 &&
            tar -xf "$distfile" && distdir=${distfile%-*-g*.tar.gz} &&
            version_sh=$("$distdir/src/getversion.sh" -s) && eval "${version_sh}" &&
            cd smartmontools-${SMARTMONTOOLS_PKG_VER} && mkdir build && cd build &&
            ../configure --with-build-info='(GHA/qemu)' \
              MAKE=gmake OBJCOPY=gobjcopy \
              SOURCE_DATE_EPOCH=$((SMARTMONTOOLS_GIT_REV_EPOCH + 1)) &&
            gmake -j4 && gmake check &&
            bin_distfile="../../smartmontools-solaris-$ver-x86_64-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz" &&
            gmake bin_distfile="$bin_distfile" bin-dist && tar -tvf "$bin_distfile" &&
            tar -xf "$bin_distfile" usr/local/sbin/smartctl &&
            echo '$' usr/local/sbin/smartctl --scan &&
            { usr/local/sbin/smartctl --scan || echo "::error::'smartctl --scan' failed"; }

      - uses: actions/upload-artifact@v7
        with:
          name: smartmontools-solaris-x86_64
          path: smartmontools-solaris-*.tar.gz
          retention-days: 90

  build-ubuntu-riscv64:
    if: ${{ contains(github.event.inputs.emulated-le-platforms, 'ubuntu-riscv64') }}
    needs: build-source-tarball
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: smartmontools-src

      - name: Build and Run (QEMU)
        uses: vmactions/ubuntu-vm@v1
        with:
          arch: riscv64
          release: "26.04"
          prepare: |
            apt-get update && apt-get install -y g++ make
          run: |
            uname -a && cat /etc/os-release &&
            ver=$(eval "$(cat /etc/os-release)" && echo "$VERSION_ID") && echo "Ubuntu $ver" &&
            distfile=$(ls -d smartmontools-*.tar.gz) &&
            test "$(echo "$distfile" | wc -l | tr -d ' ')" = 1 &&
            tar -xf "$distfile" && distdir=${distfile%-*-g*.tar.gz} &&
            version_sh=$("$distdir/src/getversion.sh" -s) && eval "${version_sh}" &&
            cd smartmontools-${SMARTMONTOOLS_PKG_VER} && mkdir build && cd build &&
            ../configure --with-build-info='(GHA/qemu)' \
              SOURCE_DATE_EPOCH=$((SMARTMONTOOLS_GIT_REV_EPOCH + 1)) &&
            make -j4 && make check &&
            bin_distfile="../../smartmontools-ubuntu-$ver-riscv64-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz" &&
            make bin_distfile="$bin_distfile" bin-dist && tar -tvf "$bin_distfile" &&
            tar -xf "$bin_distfile" usr/local/sbin/smartctl &&
            echo '$' usr/local/sbin/smartctl --scan &&
            { usr/local/sbin/smartctl --scan || echo "::error::'smartctl --scan' failed"; }

      - uses: actions/upload-artifact@v7
        with:
          name: smartmontools-ubuntu-riscv64
          path: smartmontools-ubuntu-*.tar.gz
          retention-days: 90

  build-ubuntu-s390x: # Big Endian
    if: ${{ contains(github.event.inputs.emulated-be-platforms, 'ubuntu-s390x') }}
    needs: build-source-tarball
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: smartmontools-src

      - name: Build and Run (QEMU)
        uses: vmactions/ubuntu-vm@v1
        with:
          arch: s390x
          release: "26.04"
          prepare: |
            apt-get update && apt-get install -y g++ make
          run: |
            uname -a && cat /etc/os-release &&
            ver=$(eval "$(cat /etc/os-release)" && echo "$VERSION_ID") && echo "Ubuntu $ver" &&
            distfile=$(ls -d smartmontools-*.tar.gz) &&
            test "$(echo "$distfile" | wc -l | tr -d ' ')" = 1 &&
            tar -xf "$distfile" && distdir=${distfile%-*-g*.tar.gz} &&
            version_sh=$("$distdir/src/getversion.sh" -s) && eval "${version_sh}" &&
            cd smartmontools-${SMARTMONTOOLS_PKG_VER} && mkdir build && cd build &&
            ../configure --with-build-info='(GHA/qemu)' \
              SOURCE_DATE_EPOCH=$((SMARTMONTOOLS_GIT_REV_EPOCH + 1)) &&
            make -j4 && make check &&
            bin_distfile="../../smartmontools-ubuntu-$ver-s390x-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz" &&
            make bin_distfile="$bin_distfile" bin-dist && tar -tvf "$bin_distfile" &&
            tar -xf "$bin_distfile" usr/local/sbin/smartctl &&
            echo '$' usr/local/sbin/smartctl --scan &&
            { usr/local/sbin/smartctl --scan || echo "::error::'smartctl --scan' failed"; }

      - uses: actions/upload-artifact@v7
        with:
          name: smartmontools-ubuntu-s390x
          path: smartmontools-ubuntu-*.tar.gz
          retention-days: 90
